# Generated by Django 4.2.30 on 2026-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_professional_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='user',
            name='resume_highlights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resume_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
