# Generated by Django 4.2.30 on 2026-07-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0003_question_interviewsession_question_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='video_local_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
