# Generated by Django 4.2.30 on 2026-07-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0004_interviewsession_video_local_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='conversation_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='difficulty',
            field=models.CharField(blank=True, default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='interview_mode',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('live', 'Live')], default='recorded', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='job_role',
            field=models.CharField(blank=True, default='Software Engineer', max_length=100),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='live_face_readings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
