# Generated by Django 4.2.30 on 2026-08-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0006_questionbank_userquestionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='text',
            field=models.TextField(help_text='Full question text shown to (used by) the AI interviewer as a topic anchor.'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='topic_tag',
            field=models.CharField(blank=True, help_text='Short tag, e.g. "system-design", "leadership"', max_length=80),
        ),
    ]
