# Generated by Django 4.2.30 on 2026-09-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0007_alter_questionbank_text_alter_questionbank_topic_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='candidate_strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='candidate_weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='interview_phase',
            field=models.CharField(choices=[('intro', 'Introduction'), ('behavioral', 'Behavioral'), ('technical', 'Technical'), ('situational', 'Situational'), ('closing', 'Closing')], default='intro', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='questions_asked_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='topics_covered',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
