# Generated by Django 4.2.30 on 2026-09-21 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0008_interviewsession_candidate_strengths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='coding_submissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='tab_switch_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='interview_phase',
            field=models.CharField(choices=[('intro', 'Introduction'), ('behavioral', 'Behavioral'), ('technical', 'Technical'), ('coding', 'Coding'), ('situational', 'Situational'), ('closing', 'Closing')], default='intro', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('disqualified', 'Disqualified')], db_index=True, default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_sessions.interviewsession')),
            ],
            options={
                'db_table': 'proctoring_events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
