# Generated by Django 4.2.30 on 2026-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0009_interviewsession_coding_submissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='coding_current_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='coding_questions_asked',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
