# Generated by Django 4.2.30 on 2026-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0010_interviewsession_coding_current_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='resume_highlights',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='used_resume',
            field=models.BooleanField(default=False),
        ),
    ]
