# Generated by Django 4.2.30 on 2026-09-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisreport',
            name='candidate_level',
            field=models.CharField(default='mid', max_length=20),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='evidence_quotes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='green_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='level_adjusted_overall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='level_confidence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='red_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='strict_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='verdict',
            field=models.TextField(blank=True),
        ),
    ]
